# NB

## Load and import data

In [ ]:
from src.data.make_dataset import main as get_data
from src.data.make_dataset_oversample import main as get_data_os
from src.data.preprocess import Preprocessor

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import accuracy_score,precision_score, recall_score, confusion_matrix, classification_report, roc_curve, roc_auc_score, f1_score
from src.data.make_dataset import main as get_data
from sklearn import model_selection, naive_bayes
import scipy
import matplotlib.pyplot as plt
import pickle
import joblib

In [ ]:
X_train, X_test, y_train, y_test = get_data_os("../data-dialogue/data/raw/reviews.csv")

## Prepare data for NB
add normalisation of FE features to remove negative values (NB model does not accept this)

In [ ]:
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train['cleaned_text'])
X_test_tfidf = vectorizer.transform(X_test['cleaned_text'])

X_train_tfidf = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
X_test_tfidf = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

X_train_clean = X_train.drop(['cleaned_text', 'text'], axis=1)
X_test_clean = X_test.drop(['cleaned_text', 'text'], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_clean_scaled = scaler.fit_transform(X_train_clean)
X_train_clean_scaled = pd.DataFrame(X_train_clean_scaled, columns = X_train_clean.columns)
X_test_clean_scaled = scaler.fit_transform(X_test_clean)
X_test_clean_scaled = pd.DataFrame(X_test_clean_scaled, columns = X_train_clean.columns)

X_train_concat = pd.concat([X_train_clean_scaled, X_train_tfidf], axis=1)
X_test_concat = pd.concat([X_test_clean_scaled, X_test_tfidf], axis=1)

X_train_concat = X_train_concat.loc[:, ~X_train_concat.columns.duplicated()].copy()
X_test_concat = X_test_concat.loc[:, ~X_test_concat.columns.duplicated()].copy()

In [ ]:
X_train_concat.shape #9213 features

In [ ]:
y_train

# Vanilla NB

In [ ]:
# fit the training dataset on the classifier
nb = naive_bayes.MultinomialNB()
nb.fit(X_train_concat,y_train)

### Evaluation

In [ ]:
# Make predictions on the testing set
y_pred = nb.predict(X_test_concat)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report)

# Accuracy: 0.7548209366391184
# Precision: 0.7516339869281046
# Recall: 0.9987593052109182
# f1-score: 0.8577517314864145
# Confusion Matrix: 
#  [[ 17 266]
#  [  1 805]]
# Classification Report: 
#                precision    recall  f1-score   support

#            0       0.94      0.06      0.11       283
#            1       0.75      1.00      0.86       806

#     accuracy                           0.75      1089
#    macro avg       0.85      0.53      0.49      1089
# weighted avg       0.80      0.75      0.66      1089


In [ ]:
# plot roc curve
fpr, tpr, _ = roc_curve(y_test,  y_pred)
plt.plot(fpr,tpr)
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()
auc = roc_auc_score(y_test, y_pred)
print(f"For this SVM model, the AUC score is: {auc}")
#For this SVM model, the AUC score is: 0.5294149882945051

## Set max_features=5000 for TfidfVectorizer & refit into Vanilla SVM

In [ ]:
vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = vectorizer.fit_transform(X_train['cleaned_text'])
X_test_tfidf = vectorizer.transform(X_test['cleaned_text'])

X_train_tfidf = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
X_test_tfidf = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

X_train_clean = X_train.drop(['cleaned_text', 'text'], axis=1)
X_test_clean = X_test.drop(['cleaned_text', 'text'], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_clean_scaled = scaler.fit_transform(X_train_clean)
X_train_clean_scaled = pd.DataFrame(X_train_clean_scaled, columns = X_train_clean.columns)
X_test_clean_scaled = scaler.fit_transform(X_test_clean)
X_test_clean_scaled = pd.DataFrame(X_test_clean_scaled, columns = X_train_clean.columns)

X_train_concat = pd.concat([X_train_clean_scaled, X_train_tfidf], axis=1)
X_test_concat = pd.concat([X_test_clean_scaled, X_test_tfidf], axis=1)

X_train_concat = X_train_concat.loc[:, ~X_train_concat.columns.duplicated()].copy()
X_test_concat = X_test_concat.loc[:, ~X_test_concat.columns.duplicated()].copy()

# NB with max_features (5000)

In [ ]:
# fit the training dataset on the classifier
nb = naive_bayes.MultinomialNB()
nb.fit(X_train_concat,y_train)

### Evaluation

In [ ]:
# Make predictions on the testing set
y_pred = nb.predict(X_test_concat)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1_score)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report) #better


# Accuracy: 0.7998163452708907
# Precision: 0.7876712328767124
# Recall: 0.9987593052109182
# f1-score: 0.8807439824945295
# Confusion Matrix: 
#  [[ 66 217]
#  [  1 805]]
# Classification Report: 
#                precision    recall  f1-score   support

#            0       0.99      0.23      0.38       283
#            1       0.79      1.00      0.88       806

#     accuracy                           0.80      1089
#    macro avg       0.89      0.62      0.63      1089
# weighted avg       0.84      0.80      0.75      1089


In [ ]:
# plot roc curve
fpr, tpr, _ = roc_curve(y_test,  y_pred)
plt.plot(fpr,tpr)
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()
auc = roc_auc_score(y_test, y_pred)
print(f"For this SVM model, the AUC score is: {auc}")
#For this SVM model, the AUC score is: 0.6159874264570492

## Set max_features=1000 for TfidfVectorizer & refit into Vanilla SVM

In [ ]:
vectorizer = TfidfVectorizer(max_features=1000)

X_train_tfidf = vectorizer.fit_transform(X_train['cleaned_text'])
X_test_tfidf = vectorizer.transform(X_test['cleaned_text'])

X_train_tfidf = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
X_test_tfidf = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

X_train_clean = X_train.drop(['cleaned_text', 'text'], axis=1)
X_test_clean = X_test.drop(['cleaned_text', 'text'], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_clean_scaled = scaler.fit_transform(X_train_clean)
X_train_clean_scaled = pd.DataFrame(X_train_clean_scaled, columns = X_train_clean.columns)
X_test_clean_scaled = scaler.fit_transform(X_test_clean)
X_test_clean_scaled = pd.DataFrame(X_test_clean_scaled, columns = X_train_clean.columns)

X_train_concat = pd.concat([X_train_clean_scaled, X_train_tfidf], axis=1)
X_test_concat = pd.concat([X_test_clean_scaled, X_test_tfidf], axis=1)

X_train_concat = X_train_concat.loc[:, ~X_train_concat.columns.duplicated()].copy()
X_test_concat = X_test_concat.loc[:, ~X_test_concat.columns.duplicated()].copy()

# NB with max_features (1000)

In [ ]:
# fit the training dataset on the classifier
nb = naive_bayes.MultinomialNB()
nb.fit(X_train_concat,y_train)

### Evaluation

In [ ]:
# Make predictions on the testing set
y_pred = nb.predict(X_test_concat)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report) #better

# Accuracy: 0.8420569329660239
# Precision: 0.8408602150537634
# Recall: 0.9702233250620348
# Confusion Matrix: 
#  [[135 148]
#  [ 24 782]]
# Classification Report: 
#                precision    recall  f1-score   support

#            0       0.85      0.48      0.61       283
#            1       0.84      0.97      0.90       806

#     accuracy                           0.84      1089
#    macro avg       0.84      0.72      0.76      1089
# weighted avg       0.84      0.84      0.83      1089


In [ ]:
# plot roc curve
fpr, tpr, _ = roc_curve(y_test,  y_pred)
plt.plot(fpr,tpr)
plt.ylabel('True Positive Rate')
plt.xlabel('False Positive Rate')
plt.show()
auc = roc_auc_score(y_test, y_pred)
print(f"For this SVM model, the AUC score is: {auc}")

# NB with dim reduction (SVD: 100 components)

In [ ]:
n_components = 100
svd = TruncatedSVD(n_components=n_components)
X_train_svd = svd.fit_transform(X_train_tfidf)
X_test_svd = svd.transform(X_test_tfidf)

In [ ]:
X_train_svd_df = pd.DataFrame(X_train_svd, columns=[f'svd_{i}' for i in range(n_components)])
X_test_svd_df = pd.DataFrame(X_test_svd, columns=[f'svd_{i}' for i in range(n_components)])

X_train_concat = pd.concat([X_train_clean, X_train_svd_df], axis=1)
X_test_concat = pd.concat([X_test_clean, X_test_svd_df], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_concat_svd = scaler.fit_transform(X_train_concat)
X_train_concat_svd = pd.DataFrame(X_train_concat_svd, columns = X_train_concat.columns)
X_test_concat_svd = scaler.fit_transform(X_test_concat)
X_test_concat_svd = pd.DataFrame(X_test_concat_svd, columns = X_test_concat.columns)


In [ ]:
# fit the training dataset on the classifier
nb = naive_bayes.MultinomialNB()
nb.fit(X_train_concat_svd,y_train)

In [ ]:
# Make predictions on the testing set
y_pred = nb.predict(X_test_concat_svd)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test,y_pred)
recall = recall_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)
f1_score = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1_score)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report)

# Accuracy: 0.7566574839302111
# Precision: 0.7598463016330451
# Recall: 0.9813895781637717
# Confusion Matrix: 
#  [[ 33 250]
#  [ 15 791]]
# Classification Report: 
#                precision    recall  f1-score   support

#            0       0.69      0.12      0.20       283
#            1       0.76      0.98      0.86       806

#     accuracy                           0.76      1089
#    macro avg       0.72      0.55      0.53      1089
# weighted avg       0.74      0.76      0.69      1089

# NB with oversampling of minority class

In [ ]:
X_train_os, X_test_os, y_train_os, y_test_os = get_data_os("../data-dialogue/data/raw/reviews.csv", oversample=True)

In [ ]:
#max features = 1000 was the best model thus far
vectorizer = TfidfVectorizer(max_features=1000)

X_train_tfidf = vectorizer.fit_transform(X_train_os['cleaned_text'])
X_test_tfidf = vectorizer.transform(X_test_os['cleaned_text'])

X_train_tfidf = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
X_test_tfidf = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

X_train_clean = X_train_os.drop(['cleaned_text', 'text'], axis=1)
X_test_clean = X_test_os.drop(['cleaned_text', 'text'], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_clean_scaled = scaler.fit_transform(X_train_clean)
X_train_clean_scaled = pd.DataFrame(X_train_clean_scaled, columns = X_train_clean.columns)
X_test_clean_scaled = scaler.fit_transform(X_test_clean)
X_test_clean_scaled = pd.DataFrame(X_test_clean_scaled, columns = X_train_clean.columns)

X_train_concat = pd.concat([X_train_clean_scaled, X_train_tfidf], axis=1)
X_test_concat = pd.concat([X_test_clean_scaled, X_test_tfidf], axis=1)

X_train_concat = X_train_concat.loc[:, ~X_train_concat.columns.duplicated()].copy()
X_test_concat = X_test_concat.loc[:, ~X_test_concat.columns.duplicated()].copy()

In [ ]:
# fit the training dataset on the classifier
nb = naive_bayes.MultinomialNB()
nb.fit(X_train_concat,y_train_os)

In [ ]:
# Make predictions on the testing set
y_pred = nb.predict(X_test_concat)

# Evaluate the model
accuracy = accuracy_score(y_test_os, y_pred)
precision = precision_score(y_test_os,y_pred)
recall = recall_score(y_test_os, y_pred)
conf_matrix = confusion_matrix(y_test_os, y_pred)
class_report = classification_report(y_test_os, y_pred)
f1 = f1_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report)

# Accuracy: 0.8438934802571166
# Precision: 0.9356164383561644
# Recall: 0.847394540942928
# Confusion Matrix: 
#  [[236  47]
#  [123 683]]
# Classification Report: 
#                precision    recall  f1-score   support

#            0       0.66      0.83      0.74       283
#            1       0.94      0.85      0.89       806

#     accuracy                           0.84      1089
#    macro avg       0.80      0.84      0.81      1089
# weighted avg       0.86      0.84      0.85      1089

# Evaluation:
best model = tfidf with max_features=1000 + oversampling of minority class

In [ ]:
#max features = 1000 was the best model thus far
vectorizer = TfidfVectorizer(max_features=1000)

X_train_tfidf = vectorizer.fit_transform(X_train_os['cleaned_text'])
X_test_tfidf = vectorizer.transform(X_test_os['cleaned_text'])

X_train_tfidf = pd.DataFrame(X_train_tfidf.toarray(), columns=vectorizer.get_feature_names_out())
X_test_tfidf = pd.DataFrame(X_test_tfidf.toarray(), columns=vectorizer.get_feature_names_out())

X_train_clean = X_train_os.drop(['cleaned_text', 'text'], axis=1)
X_test_clean = X_test_os.drop(['cleaned_text', 'text'], axis=1)

#added this
scaler = MinMaxScaler(feature_range=(0, 1))
X_train_clean_scaled = scaler.fit_transform(X_train_clean)
X_train_clean_scaled = pd.DataFrame(X_train_clean_scaled, columns = X_train_clean.columns)
X_test_clean_scaled = scaler.fit_transform(X_test_clean)
X_test_clean_scaled = pd.DataFrame(X_test_clean_scaled, columns = X_test_clean.columns)

X_train_concat = pd.concat([X_train_clean_scaled, X_train_tfidf], axis=1)
X_test_concat = pd.concat([X_test_clean_scaled, X_test_tfidf], axis=1)

X_train_concat = X_train_concat.loc[:, ~X_train_concat.columns.duplicated()].copy()
X_test_concat = X_test_concat.loc[:, ~X_test_concat.columns.duplicated()].copy()

# Parameter Tuning

In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold

cv_method = RepeatedStratifiedKFold(n_splits=3, 
                                    n_repeats=1, 
                                    random_state=999)

from sklearn.preprocessing import PowerTransformer

alphas = [0.1, 0.3, 0.5, 0.7, 1.0]
params_NB = {'alpha': alphas, 'fit_prior' : [True, False], 'class_prior' : [None, [.1,.9],[.2, .8]]}

gs_NB = GridSearchCV(estimator=nb, 
                     param_grid=params_NB, 
                     cv=cv_method,
                     verbose=1, 
                     scoring='accuracy')

gs_NB.fit(X_train_concat, y_train_os)


In [ ]:
gs_NB.best_params_ #{'alpha': 0.5, 'class_prior': None, 'fit_prior': True}

In [ ]:
grid_predictions = gs_NB.predict(X_test_concat)

# Evaluate the model
accuracy = accuracy_score(y_test, grid_predictions)
precision = precision_score(y_test,grid_predictions)
recall = recall_score(y_test, grid_predictions)
conf_matrix = confusion_matrix(y_test, grid_predictions)
class_report = classification_report(y_test, grid_predictions)
f1 = f1_score(y_test, grid_predictions)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("f1-score:", f1)
print("Confusion Matrix: \n", conf_matrix)
print("Classification Report: \n", class_report)

[FE] finished lowercase count...
[FE] finished uppercase count...
[FE] finished uppercase ratio...
[FE] finished punc count...
[FE] finished pos tags...
[FE] finished pos tag count...
[FE] finished tokenized_untokenized count...
[FE] finished num words misspelled...
[FE] finished polarity...
[FE] finished subjectivity...
[FE] finished pos neg count...

(4355, 9213)

MultinomialNB
MultinomialNB()
Accuracy: 0.7548209366391184
Precision: 0.7516339869281046
Recall: 0.9987593052109182
f1-score: 0.8577517314864145
Confusion Matrix: 
 [[ 17 266]
 [  1 805]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.94      0.06      0.11       283
           1       0.75      1.00      0.86       806

    accuracy                           0.75      1089
   macro avg       0.85      0.53      0.49      1089
weighted avg       0.80      0.75      0.66      1089


For this SVM model, the AUC score is: 0.5294149882945051

MultinomialNB
MultinomialNB()
Accuracy: 0.7998163452708907
Precision: 0.7876712328767124
Recall: 0.9987593052109182
f1-score: 0.8807439824945295
Confusion Matrix: 
 [[ 66 217]
 [  1 805]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.99      0.23      0.38       283
           1       0.79      1.00      0.88       806

    accuracy                           0.80      1089
   macro avg       0.89      0.62      0.63      1089
weighted avg       0.84      0.80      0.75      1089


For this SVM model, the AUC score is: 0.6159874264570492

MultinomialNB
MultinomialNB()
Accuracy: 0.7566574839302111
Precision: 0.7598463016330451
Recall: 0.9813895781637717
Confusion Matrix: 
 [[ 33 250]
 [ 15 791]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.69      0.12      0.20       283
           1       0.76      0.98      0.86       806

    accuracy                           0.76      1089
   macro avg       0.72      0.55      0.53      1089
weighted avg       0.74      0.76      0.69      1089

[FE] finished lowercase count...
[FE] finished uppercase count...
[FE] finished uppercase ratio...
[FE] finished punc count...
[FE] finished pos tags...
[FE] finished pos tag count...
[FE] finished tokenized_untokenized count...
[FE] finished num words misspelled...
[FE] finished polarity...
[FE] finished subjectivity...
[FE] finished pos neg count...

MultinomialNB
MultinomialNB()
Accuracy: 0.8420569329660239
Precision: 0.8408602150537634
Recall: 0.9702233250620348
Confusion Matrix: 
 [[135 148]
 [ 24 782]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.85      0.48      0.61       283
           1       0.84      0.97      0.90       806

    accuracy                           0.84      1089
   macro avg       0.84      0.72      0.76      1089
weighted avg       0.84      0.84      0.83      1089


For this SVM model, the AUC score is: 0.723627563591088

MultinomialNB
MultinomialNB()
Accuracy: 0.8438934802571166
Precision: 0.9356164383561644
Recall: 0.847394540942928
Confusion Matrix: 
 [[236  47]
 [123 683]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.66      0.83      0.74       283
           1       0.94      0.85      0.89       806

    accuracy                           0.84      1089
   macro avg       0.80      0.84      0.81      1089
weighted avg       0.86      0.84      0.85      1089

# Fitting 3 folds for each of 30 candidates, totalling 90 fits
# GridSearchCV
# estimator: MultinomialNB

# MultinomialNB
# {'alpha': 0.5, 'class_prior': None, 'fit_prior': True}
# [[237  46]
#  [124 682]]
#               precision    recall  f1-score   support

#            0       0.66      0.84      0.74       283
#            1       0.94      0.85      0.89       806

#     accuracy                           0.84      1089
#    macro avg       0.80      0.84      0.81      1089
# weighted avg       0.86      0.84      0.85      1089

# Accuracy: 0.8438934802571166
# Precision: 0.9368131868131868
# Recall: 0.8461538461538461
# Confusion Matrix: 
#  [[237  46]
#  [124 682]]

In [ ]:
gs_NB.best_estimator_ 
# MultinomialNB(alpha=0.5)

In [ ]:
# save best parameters
joblib.dump(gs_NB.best_estimator_, 'naive_bayes_best_model.pkl')

# Load Saved Model

In [ ]:
saved_model = joblib.load('naive_bayes_best_model.pkl')

In [ ]:
saved_model